import type { AchievementDef } from '../types/shared';

export const ACHIEVEMENT_DEFINITIONS: AchievementDef[] = [
  // --- Hábitos ---
  {
    id: 'first_habit',
    name: 'Primer paso',
    description: 'Completaste tu primer hábito',
    icon: '🌱',
    type: 'individual',
    category: 'habits',
    condition: 'complete_1_habit',
  },
  {
    id: 'habits_10',
    name: 'En camino',
    description: 'Completaste 10 hábitos en total',
    icon: '📈',
    type: 'individual',
    category: 'habits',
    condition: 'complete_10_habits',
  },
  {
    id: 'habits_50',
    name: 'Disciplinado',
    description: 'Completaste 50 hábitos en total',
    icon: '⚡',
    type: 'individual',
    category: 'habits',
    condition: 'complete_50_habits',
  },
  {
    id: 'habits_100',
    name: 'Centenario',
    description: 'Completaste 100 hábitos en total',
    icon: '💯',
    type: 'individual',
    category: 'habits',
    condition: 'complete_100_habits',
  },
  {
    id: 'streak_7',
    name: 'Constancia',
    description: '7 días seguidos con un hábito',
    icon: '🔥',
    type: 'individual',
    category: 'habits',
    condition: 'streak_7',
  },
  {
    id: 'streak_14',
    name: 'Racha de fuego',
    description: '14 días seguidos con un hábito',
    icon: '🔥🔥',
    type: 'individual',
    category: 'habits',
    condition: 'streak_14',
  },
  {
    id: 'streak_30',
    name: 'Imparable',
    description: '30 días seguidos con un hábito',
    icon: '👑',
    type: 'individual',
    category: 'habits',
    condition: 'streak_30',
  },

  // --- Carreras ---
  {
    id: 'first_run',
    name: 'Primera carrera',
    description: 'Registraste tu primera sesión de running',
    icon: '🏃',
    type: 'individual',
    category: 'running',
    condition: 'first_run',
  },
  {
    id: 'run_5k',
    name: '5K',
    description: 'Corriste 5 km o más en una sola sesión',
    icon: '🎯',
    type: 'individual',
    category: 'running',
    condition: 'run_5k',
  },
  {
    id: 'total_42k',
    name: 'Maratonista',
    description: 'Acumulaste 42 km corriendo en total',
    icon: '🏅',
    type: 'individual',
    category: 'running',
    condition: 'total_42k',
  },
  {
    id: 'caco_complete',
    name: 'Plan completo',
    description: 'Completaste las 11 semanas del Método CaCo',
    icon: '🏆',
    type: 'individual',
    category: 'running',
    condition: 'caco_complete',
  },

  // --- Diario ---
  {
    id: 'first_journal',
    name: 'Escritor',
    description: 'Escribiste tu primera entrada en el diario',
    icon: '✏️',
    type: 'individual',
    category: 'journal',
    condition: 'first_journal',
  },
  {
    id: 'journal_7',
    name: 'Diario de 7',
    description: 'Escribiste 7 entradas en el diario',
    icon: '📓',
    type: 'individual',
    category: 'journal',
    condition: 'journal_7',
  },
  {
    id: 'journal_30',
    name: 'Cronista',
    description: 'Escribiste 30 entradas en el diario',
    icon: '📖',
    type: 'individual',
    category: 'journal',
    condition: 'journal_30',
  },

  // --- Pareja ---
  {
    id: 'couple_sync',
    name: 'Equipo',
    description: 'Ambos completaron todos los hábitos del mismo día',
    icon: '💕',
    type: 'couple',
    category: 'couple',
    condition: 'both_complete_day',
  },
  {
    id: 'couple_streak_7',
    name: 'Pareja en fuego',
    description: '7 días seguidos ambos completando hábitos',
    icon: '🔥💕',
    type: 'couple',
    category: 'couple',
    condition: 'couple_streak_7',
  },
  {
    id: 'couple_run',
    name: 'Corren juntos',
    description: 'Ambos corrieron en el mismo día',
    icon: '👫',
    type: 'couple',
    category: 'couple',
    condition: 'couple_same_day_run',
  },
  {
    id: 'shared_todos_10',
    name: 'Compañeros',
    description: 'Completaron 10 mandados compartidos',
    icon: '🤝',
    type: 'couple',
    category: 'couple',
    condition: 'shared_todos_10',
  },

  // --- General ---
  {
    id: 'explorer',
    name: 'Explorador',
    description: 'Usaste todas las secciones de la app',
    icon: '🧭',
    type: 'individual',
    category: 'general',
    condition: 'use_all_sections',
  },
];

export const ACHIEVEMENT_CATEGORY_LABELS: Record<string, string> = {
  habits: 'Hábitos',
  running: 'Carreras',
  journal: 'Diario',
  couple: 'Pareja',
  general: 'General',
};

export const MOOD_OPTIONS = [
  { value: 1, emoji: '😫', label: 'Terrible' },
  { value: 2, emoji: '😕', label: 'Difícil' },
  { value: 3, emoji: '😐', label: 'Normal' },
  { value: 4, emoji: '😊', label: 'Bien' },
  { value: 5, emoji: '🤩', label: 'Increíble' },
] as const;
